modLoader="javafml"
loaderVersion="[52,)"
license="GPLv3"

[[mods]]
modId="respect_socks5_options"
version="1.0.0"
displayName="Respect Socks5 Options"
credits="RespectProxyOptions for fabric"
authors="commandblock2"

description='''
Adds partial socks5 proxy support for Forge.
This mod respects -DsocksProxyHost and -DsocksProxyPort.
'''

[[dependencies.respect_socks5_options]]
    modId="forge"
    mandatory=true
    versionRange="[52,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.respect_socks5_options]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"
